ALTER TABLE ProfileEnvelope ADD [CreatedTime] DATETIME NOT NULL
GO
ALTER TABLE [ProfileEnvelope] ALTER COLUMN [Name] VARCHAR(100) NOT NULL
GO
ALTER TABLE [ProfileEnvelope] ALTER COLUMN [Payload] VARCHAR(MAX) NOT NULL
GO